name: dietify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4
  cached_network_image: 3.4.1
  smooth_page_indicator: ^1.2.1
  sizer: ^3.0.5
  animate_do: ^4.2.0
  flutter_svg: ^2.0.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env
