name: dietify
description: "Dietify is a fitness and nutrition app that helps users track their health and share recipes."
publish_to: 'none'
version: 0.5.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4
  cached_network_image: 3.4.1
  smooth_page_indicator: ^1.2.1
  sizer: ^3.0.5
  animate_do: ^4.2.0
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  loading_animation_widget: ^1.3.0
  path_provider: ^2.1.2
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  convex_bottom_bar: ^3.2.0
  fl_chart: ^0.70.2
  http: ^1.3.0
  google_sign_in: ^6.3.0
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.1.0
  workmanager: ^0.5.2
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/dietify.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env
