// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3SQXyvvmiEjVZ9BOlqkp0zJuoOWAj0Uo',
    appId: '1:878716108634:web:172f20a78d2b09ca783d63',
    messagingSenderId: '878716108634',
    projectId: 'dietify-f1c9a',
    authDomain: 'dietify-f1c9a.firebaseapp.com',
    storageBucket: 'dietify-f1c9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6A47Ir3_opyxMRrNOPn6Tq-gnMDe_jqQ',
    appId: '1:878716108634:android:5e8fad81233165de783d63',
    messagingSenderId: '878716108634',
    projectId: 'dietify-f1c9a',
    storageBucket: 'dietify-f1c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFTG5A4dTfnxKqXN26Fvd3aoSsIK2Xu0c',
    appId: '1:878716108634:ios:b3824c5a51ad8b0e783d63',
    messagingSenderId: '878716108634',
    projectId: 'dietify-f1c9a',
    storageBucket: 'dietify-f1c9a.appspot.com',
    iosBundleId: 'com.example.dietify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFTG5A4dTfnxKqXN26Fvd3aoSsIK2Xu0c',
    appId: '1:878716108634:ios:b3824c5a51ad8b0e783d63',
    messagingSenderId: '878716108634',
    projectId: 'dietify-f1c9a',
    storageBucket: 'dietify-f1c9a.appspot.com',
    iosBundleId: 'com.example.dietify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3SQXyvvmiEjVZ9BOlqkp0zJuoOWAj0Uo',
    appId: '1:878716108634:web:7b2a2d1303194db4783d63',
    messagingSenderId: '878716108634',
    projectId: 'dietify-f1c9a',
    authDomain: 'dietify-f1c9a.firebaseapp.com',
    storageBucket: 'dietify-f1c9a.appspot.com',
  );
}
