name: Run Flutter Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Create .env file from example
      run: cp .env.example .env

    - name: Run tests
      run: flutter test
